// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCozOKzlK46l0iGmoXXf-j_vW873JJAcxo',
    appId: '1:360695457574:web:8d1e31515c93d14e7283e7',
    messagingSenderId: '360695457574',
    projectId: 'furniture-auth-8b478',
    authDomain: 'furniture-auth-8b478.firebaseapp.com',
    storageBucket: 'furniture-auth-8b478.firebasestorage.app',
    measurementId: 'G-BFYJEYCBG7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl4dT0OXLTORMbWru7TykOEwYT6nmG4hE',
    appId: '1:360695457574:android:d4228d5aa07135ee7283e7',
    messagingSenderId: '360695457574',
    projectId: 'furniture-auth-8b478',
    storageBucket: 'furniture-auth-8b478.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBWAXyJmlDMzNXUx7jqp50lmq61N-rZMQ',
    appId: '1:360695457574:ios:ff7eb92f897338fa7283e7',
    messagingSenderId: '360695457574',
    projectId: 'furniture-auth-8b478',
    storageBucket: 'furniture-auth-8b478.firebasestorage.app',
    iosBundleId: 'com.example.furnitureApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBWAXyJmlDMzNXUx7jqp50lmq61N-rZMQ',
    appId: '1:360695457574:ios:ff7eb92f897338fa7283e7',
    messagingSenderId: '360695457574',
    projectId: 'furniture-auth-8b478',
    storageBucket: 'furniture-auth-8b478.firebasestorage.app',
    iosBundleId: 'com.example.furnitureApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCozOKzlK46l0iGmoXXf-j_vW873JJAcxo',
    appId: '1:360695457574:web:f36659ada632e24b7283e7',
    messagingSenderId: '360695457574',
    projectId: 'furniture-auth-8b478',
    authDomain: 'furniture-auth-8b478.firebaseapp.com',
    storageBucket: 'furniture-auth-8b478.firebasestorage.app',
    measurementId: 'G-T0XHL29R7T',
  );
}
